name: learningapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # STATE MANAGEMENT
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  nb_utils: ^4.4.8
  delayed_display: ^2.0.0
  fluttertoast: ^8.0.8

  # Base
  flutter_vector_icons: ^1.0.0

  # Common
  share: ^2.0.4
  url_launcher: 6.0.17
  http: ^0.13.3
  package_info: ^2.0.2
  font_awesome_flutter: ^9.2.0

  # IMAGES
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  html: ^0.15.0
  intl: ^0.17.0
  # MAP
  #google_maps_flutter: ^2.0.6
  #geolocator: ^7.3.1
  geocoding: ^2.0.0
  # WEB TOOLS
  webview_flutter: ^2.0.8
  responsive_framework: ^0.1.4
  rive: ^0.7.33
  firebase_core: ^1.8.0
  firebase_storage:
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.0
  provider:
  woocommerce:
    git:
      url: git://github.com/abhinavmarwaha/woocommerce.git
      ref: 0093c305180ea28ecfdc5d85dbdd4ce699821187
  razorpay_flutter: ^1.1.1
  flutter_spinkit:
  top_snackbar_flutter: 1.0.0
  flash_card: ^0.0.5
  flip_board: ^0.6.1
  lint: ^1.5.3

  #clustering_google_maps: ^0.1.2
  #image_picker_gallery_camera: 0.1.6

  #Temporary disabled due to lake of null safety
  #charts_flutter: ^0.11.0
  #geocoder: 0.2.1
  #geohash: ^0.2.1
  #snaplist: 0.1.8
  #lipsum: 1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0
   #flutter packages pub run build_runner build --delete-conflicting-outputs

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/fruits/
    - assets/fruits/Apple.riv
    - assets/paypal.png
    - assets/razorpay.png
    - assets/payment.png
    - images/icons/
    - images/learnerimage/
    - images/learnerimage/learner_ic_logout.svg
    - images/ic_profile.png
    - images/ic_alfatihah.png
    - images/ic_comic.png
    - images/ic_quiz.png
    - images/learnerimage/learner_walk_1.png
    - assets/images/LikeButton/
    - images/ic_comingsoon.png
    - assets/png/animal/bear.png
    - assets/png/animal/camel.png
    - assets/png/animal/cat.png
    - assets/png/animal/chicken.png
    - assets/png/animal/cow.png
    - assets/png/animal/dog.png
    - assets/png/animal/elephent.png
    - assets/png/animal/horse.png
    - assets/png/animal/lion.png
    - assets/png/animal/sheep.png
    - assets/png/animal/snake.png
    - assets/png/animal/whale.png
    - assets/png/occupation/architek.png
    - assets/png/occupation/chef.png
    - assets/png/occupation/doctor.png
    - assets/png/occupation/fire fighter.png
    - assets/png/occupation/pilot.png
    - assets/png/occupation/police man.png
    - assets/png/occupation/sales woman.png
    - assets/png/occupation/teacher.png
    - assets/png/vehicle/ambulance.png
    - assets/png/vehicle/bus.png
    - assets/png/vehicle/bycycle.png
    - assets/png/vehicle/car.png
    - assets/png/vehicle/firetruck.png
    - assets/png/vehicle/helicopter.png
    - assets/png/vehicle/ambulance.png
    - assets/png/vehicle/hot air ballon.png
    - assets/png/vehicle/motocycle.png
    - assets/png/vehicle/plain.png
    - assets/png/vehicle/police car.png
    - assets/png/vehicle/rocket.png
    - assets/png/vehicle/ship.png
    - assets/png/vehicle/ship.png
    - assets/png/vehicle/train.png
    - assets/png/vehicle/truck.png
    - assets/png/vehicle/van.png
    - assets/png/languages/uk_flag.png
    - assets/png/languages/korea_flag.png
    - assets/png/languages/japan_flag.png
    - assets/png/languages/malaysia_flag.png
    - assets/png/languages/china_flag.png
    - assets/png/languages/turkey_flag.png
    - assets/comic/arabic/1_arabic.png
    - assets/comic/arabic/2_arabic.png
    - assets/comic/arabic/3_arabic.png
    - assets/comic/arabic/4_arabic.png
    - assets/comic/eng/1_eng.png
    - assets/comic/eng/2_eng.png
    - assets/comic/eng/3_eng.png
    - assets/comic/eng/4_eng.png
    - assets/comic/japan/1_japan.png
    - assets/comic/japan/2_japan.png
    - assets/comic/japan/3_japan.png
    - assets/comic/japan/4_japan.png
    - assets/applogo.png